apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ostiari-gateway.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "ostiari-gateway.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  OSTIARI_GATEWAY_ID: {{ .Values.gateway.id | quote }}
  OSTIARI_CONTROL_PLANE_URL: {{ .Values.gateway.controlPlaneUrl | quote }}
  OSTIARI_PORT: {{ .Values.gateway.port | quote }}
